### ISSUE TITLE
Javascript is required to use the site

### ISSUE THREAD

**Issue by mrozo** [hs3city/hs3city.github.io#20]
When javascript is disabled, the page is unusable - every subpage is covered by full screen welcome page (see the screenshot below presenting /members subpage - notice the url bar and active no-script plugin)

![/members subpage](https://user-images.githubusercontent.com/2971377/34874665-4c626386-f79a-11e7-9eb1-bd58234973c4.png)

**Comment by not7cd** [comment]
Możliwe, że można usunąć ten problem dodając jeden `if` w templatce. JS najpewniej usuwa jakąś klasę css.

**Comment by not7cd** [comment]
Działa
