### ISSUE TITLE
hs3.pl -> hs3city.github.io

### ISSUE THREAD

**Issue by not7cd** [hs3city/hs3city.github.io#5]
Jest to standard na githubie.
Podpinając do tego repo domenę hs3.pl (apex domain) to repo będzie stanowiło stronę główną, a inne repozytoria w organizacji będa automatycznie podpięte pod hs3.pl/nazwa-repo.
https://help.github.com/articles/about-supported-custom-domains/
https://help.github.com/articles/setting-up-an-apex-domain-and-www-subdomain/

**Comment by ksiadz** [comment]
Zmieniłem nazwę repo.

**Comment by not7cd** [comment]
Jeszcze domena xD
